# Generated by Django 3.2.11 on 2022-02-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220131_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(error_messages={'unique': 'Указанный ингридиент уже создан.'}, max_length=200, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
