# Generated by Django 3.2.11 on 2022-03-07 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220306_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('recipe__name',), 'verbose_name': 'Ингредиент-количество для рецепта', 'verbose_name_plural': 'Ингредиенты с количествами для рецепта'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='уникальность пары ингридиент-единица измерения',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='уникальность ингридиента в рецепте',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='количество ингридиента должно быть больше 1',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipe', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Количество ингредиента должно быть более 0.')], verbose_name='Количество ингредиента в выбранных единицах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientInRecipe', to='recipes.Ingredient', verbose_name='Ингредиент с указанием количества для рецепта'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='уникальность пары ингредиент-единица измерения'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='уникальность ингредиента в рецепте'),
        ),
    ]
