# Generated by Django 3.2.11 on 2022-02-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220221_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='IngredientInRecipe',
        ),
    ]
