# Generated by Django 3.2.11 on 2022-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220201_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Указанное имя тега уже существует.'}, max_length=200, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=7, null=True, verbose_name='Цвет в кодировке HEX')),
                ('slug', models.SlugField(error_messages={'unique': 'Указанный слаг уже существует.'}, max_length=200, unique=True, verbose_name='Слаг тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='ingridientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингридиент-количество для рецепта', 'verbose_name_plural': 'Ингридиенты с количествами для рецепта'},
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='уникальность имя тега-слаг'),
        ),
    ]
