# Generated by Django 3.2.11 on 2022-03-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredientinrecipe_уникальность ингредиента в рецепте'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='уникальность ингредиента в рецепте'),
        ),
    ]
