# Generated by Django 3.2.11 on 2022-03-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredientinrecipe_уникальность ингредиента в рецепте'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteList',
        ),
    ]
