# Generated by Django 3.2.11 on 2022-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220201_1247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='уникальность имя тега-слаг',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='уникальность пары тег-слаг'),
        ),
    ]
