# Generated by Django 3.2.11 on 2022-03-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_delete_favoritelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
