# Generated by Django 3.2.11 on 2022-01-29 18:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user_subscriber', django.db.models.expressions.F('user_author')), _negated=True), name='banning_subscriptions_to_yourself'),
        ),
    ]
