# Generated by Django 3.2.11 on 2022-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_delete_favoritelist'),
        ('users', '0002_auto_20220221_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_recipes',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
    ]
