# Generated by Django 3.2.11 on 2022-03-29 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220329_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.ManyToManyField(through='users.Subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
