# Generated by Django 3.2.11 on 2022-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favourite_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favourite_recipes',
            new_name='favorite_recipes',
        ),
    ]
