# Generated by Django 3.2.11 on 2022-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_shoppinglist'),
        ('users', '0004_rename_favourite_recipes_user_favorite_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_recipes',
            field=models.ManyToManyField(related_name='shoppings', to='recipes.Recipe', verbose_name='Рецепты в списке покупок'),
        ),
    ]
